// styles.js
import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    marginTop: 50,
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  scrollContainer: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  card: {
    height: 100,
    marginTop: 50,
    marginVertical: 4,
    marginHorizontal: 16,
    borderRadius: 15,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  textContainer: {
    flex: 0,
    top: 0,
    left: 0,
    position: 'absolute',
    backgroundColor: 'rgba(255, 255, 255, 0.9)',  // semi-transparent white
    paddingHorizontal: 24,
    paddingVertical: 8,
    borderRadius: 15,
    shadowColor: '#000',  // Optional for better glass effect
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 0.41,
    elevation: 2,
    borderColor: 'black',
  },
  
  infoText: {
    color: 'black',
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  normalDot: {
    height: 8,
    width: 8,
    borderRadius: 4,
    backgroundColor: 'lightblue',
    marginHorizontal: 4,
  },
  indicatorContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 10,
  },
  gridContainer: {
    flex: 1,
    flexDirection: 'column',
    margin: 16,
    backgroundColor: 'transparent',
    padding: 5,
    borderRadius: 5,
  },
  gridRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  gridBox: {
    flex: 1,
    height: 70,
    marginHorizontal: 4,
    backgroundColor: '#75d660c4',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 15,
  },
  gridBoxss: {
    flex: 2,
    height: 50,
    marginHorizontal: 4,
    backgroundColor: '#75d660c4',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 50,
  },
  gridBoxs: {
    flex: 2,
    height: 150,
    marginHorizontal: 4,
    backgroundColor: '#75d660c4',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 15,
  },
  TextTop: {
    flex: 1,
    fontSize: 15,
    fontWeight: 'bold',
    right: 15,
    textAlign: 'left',
    color: 'brown',
    position: 'absolute',
  },
  Texts: {
    fontSize: 20,
    fontWeight: 'bold',
    textAlign: 'left',
    marginTop: 10,
    marginLeft: 20,
  },
  image: {
    width: 70,
    height: 200,
    resizeMode: 'cover',
    left: 0,
    position: 'absolute',
    borderRadius: 15,
  },
});
